chain_name: xylo_rarm
chain_root: HeadPitch_link
chain_tip: r_stick
marker_type: circle
marker_frame: r_tip
xylo_rarm_marker_radius: 0.011

marker_transform_source: tf   # 'tf' or 'urdf' (optional; if not set, default is 'urdf')