# Choose which parts should be calibrated:
# - true: initial parameters are loaded, optimized and updated
# - false: initial parameters are used and written back, but not modified 
calibrate_joint_offsets: true
calibrate_camera_transform: true
calibrate_camera_intrinsics: true
calibrate_marker_transform: true

# Filename suffixes for the calibration files:
# The final filename will be: robot_name + "_" + suffix
# where robot_name will be taken from the currently loaded urdf robot model
# and suffix is the value of the following parameters.
joint_offsets_filename_suffix: calibration_joint_offsets.xacro
camera_transform_filename_suffix: calibration_camera_transform.xacro
urdf_filename_suffix: robot_model_calibrated.xml
marker_transforms_filename_suffix: calibration_marker_transformations.xacro
camera_intrnsics_filename: nao_bottom_640x480.yaml

### Optimization parameters:
# Number of iterations for the optimization algorithm:
max_iterations: 150
# debug flag:
debug_optimization: true