rarm001:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.326166, -0.138471, 0.0584105, -0.191637, 0.361994, 0.895718, -0.410924]

rarm002:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.158075, 0.200451, 0.305652, 0.25282, 0.0518579, 0.656635, 0.0728446]

rarm003:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.368643, -0.574901, 0.696955, -0.414336, 1.59607, 1.15601, -0.849082]

rarm004:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.122366, -0.59549, 1.23725, -0.0577785, 1.42616, 1.18415, -0.89668]

rarm005:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.116886, -0.689383, 1.08627, -0.466985, 1.06538, 1.16229, -0.425841]

rarm006:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.50864, -0.854618, 0.786064, -0.693442, 1.60239, 1.28008, -0.495684]

rarm007:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.616493, -0.53923, -0.961555, -0.568059, -0.922082, 1.50921, 0.756649]

rarm008:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.498155, -0.857479, 0.265705, -1.19805, 0.27138, 1.48628, 0.405863]

rarm009:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.500449, -0.912931, 0.0534393, -0.820821, 0.513459, 1.11897, -0.164435]

rarm010:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.381748, -0.478826, -0.384807, -0.524068, -0.341516, 1.27821, 0.0223979]

rarm011:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.165467, -0.828083, 1.04404, -0.714224, 1.15886, 1.16989, -0.471747]

rarm012:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.517355, -0.95706, 0.345654, 0.00453155, 1.82695, 1.50829, -0.990036]

rarm013:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.211582, -0.640147, 0.368715, -0.960505, 0.420433, 1.2028, -0.34862]

rarm014:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.657174, -0.957671, -0.792557, -1.01717, -0.747136, 1.43036, 0.308147]

rarm015:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.599301, -0.85429, -0.587748, -1.1244, -0.165356, 1.41432, 0.0358614]

rarm016:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.494571, -0.722032, 0.00203915, -1.02827, -0.0624675, 1.18481, 0.355598]

rarm017:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.577067, -1.26362, -0.20606, -1.2624, 0.317198, 1.35181, -0.31626]

rarm018:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.200873, -0.569426, 0.443315, -0.648998, 0.662698, 1.32595, -0.299593]

rarm019:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.280177, -0.503405, 0.533211, -0.203433, 0.845289, 0.841426, -0.593408]

rarm020:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.272189, -0.874473, -0.309746, -1.1488, -0.861376, 1.49169, 0.483193]

rarm021:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.165259, -0.718879, 0.707917, -0.243326, 0.883902, 1.12309, -0.00875881]

rarm022:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.185572, -0.836475, 0.62706, -1.19308, 0.609006, 1.45336, -0.269606]

rarm023:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.358339, -0.424457, 0.428883, -0.180695, 1.08714, 0.915547, -0.555722]

rarm024:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.584493, -0.64245, 0.424786, -0.262267, 1.46618, 1.21142, -0.490175]

rarm025:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.00023448, -0.350358, 0.89862, 0.275299, 1.1157, 0.838174, -0.681948]

rarm026:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.671401, -1.92672, 1.98044, -1.16737, -1.87917, 1.5401, 0.119198]

rarm027:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.655676, -2.01662, -1.90175, -1.30162, 0.767604, 1.44248, -0.914341]

rarm028:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0607932, -0.790777, 1.24035, -0.328742, 1.95745, 1.44533, -0.846854]

rarm029:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.470745, -2.0047, 1.87069, -0.335319, -0.323451, 1.26921, -0.0527394]

rarm030:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.266795, -0.462509, 1.22735, -0.0426742, 1.31013, 1.11455, -0.870213]

rarm031:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.412531, -0.836809, 0.678727, -0.912872, 1.38899, 1.19271, -0.245601]

rarm032:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.243912, -0.493997, 1.27675, -0.363702, 1.01588, 1.02617, -0.680617]

rarm033:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.52618, -0.878592, 1.11606, -1.14263, 1.47317, 1.40374, 0.208986]

rarm034:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.435259, -0.975867, 0.889105, -0.459647, 1.82586, 1.44303, -0.908152]

rarm035:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0336729, -0.638674, 0.88616, -0.647885, 0.829928, 1.14924, -0.438895]

rarm036:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0313934, -0.683404, 0.985112, -0.00740479, 1.60125, 1.31877, -1.08223]

rarm037:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.140271, -0.774705, 0.0494561, -0.825898, -0.363119, 1.41639, 0.487851]

rarm038:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.421969, -0.927501, 1.29229, -0.875922, 1.73188, 1.40327, -0.174618]

rarm039:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.646234, -1.89726, -1.83513, -1.19903, 0.681954, 1.46561, -0.209836]

rarm040:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.371481, -0.661873, 1.76929, -0.383891, 1.00356, 1.35679, -0.584587]

rarm041:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.300489, -0.776407, 0.587804, -0.514646, 0.55031, 1.1203, -0.137495]

rarm042:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.511874, -0.878148, 0.20633, -0.87144, 0.946025, 1.08271, -0.395388]

rarm043:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.65428, -1.856, -0.915209, -1.28476, 1.74535, 1.53293, -0.853726]

rarm044:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.197595, -0.757724, 0.862051, -0.370847, 1.16472, 1.06528, -0.610398]

rarm045:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.599851, -0.679102, -0.138916, -0.876716, -0.0280673, 1.45133, 0.545879]

rarm046:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.480738, -0.610869, 0.277386, -0.759199, 0.24094, 1.13325, 0.462247]

rarm047:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.447194, -0.854189, 0.812843, -0.404141, 1.81704, 1.53814, -0.885761]

rarm048:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.530191, -1.09013, -0.89015, -1.15901, -0.863629, 1.49038, 0.674087]

rarm049:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.63926, -1.07983, 0.211014, -0.482266, 1.52963, 1.0778, -0.699265]

rarm050:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.512548, -1.19065, 0.62071, -0.881142, 1.1527, 1.2281, -0.0312021]

