larm001:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.668659, 1.30245, 0.784796, 0.666461, -1.79309, -1.45566, 0.205519]

larm002:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.338201, 0.179776, 0.770689, 0.21731, -0.105433, -1.34058, -0.574378]

larm003:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.506674, 0.8587, 0.818405, 0.647115, 0.1937, -1.47444, 0.0793509]

larm004:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.286827, -0.00784091, 0.982156, -0.166022, -0.237538, -1.38757, -0.575966]

larm005:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.66313, 0.252345, 0.101215, 0.191742, -0.852223, -1.02074, 0.277943]

larm006:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.56856, 0.101556, -0.0157793, -0.296631, -0.263369, -1.24723, -0.690148]

larm007:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.581219, 0.369898, 0.308087, 0.00282423, -1.26081, -1.24642, 0.2502]

larm008:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.414324, 0.878897, 0.7362, 0.302275, -1.02852, -1.29533, -0.153522]

larm009:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.521418, 0.786679, 0.927132, 0.779272, -1.60513, -1.3106, 0.10816]

larm010:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.597558, 0.859573, 0.442867, 1.07071, -0.986752, -1.26608, 0.348192]

larm011:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.0199034, 0.579183, 1.05503, 0.177434, -1.04833, -1.35347, 0.729978]

larm012:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.589978, 0.948084, 0.820473, 1.04967, -1.38118, -1.53018, -0.00704488]

larm013:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.490784, 0.958023, -0.853421, 1.27049, 0.549004, -1.45224, -0.0575977]

larm014:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.620383, 1.30989, 0.952514, 0.993648, -1.68768, -1.48553, 0.557575]

larm015:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.422975, 0.529632, 0.6484, 0.606854, -0.990388, -1.24221, 0.0973426]

larm016:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.4956, 0.976383, 1.24079, 1.24062, -1.73149, -1.54339, 0.29978]

larm017:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.576732, 0.798545, 0.262043, 0.977228, -0.43407, -1.31281, -0.18851]

larm018:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.527654, 0.278214, -0.0582645, 0.386668, -0.170589, -1.1189, 0.210087]

larm019:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.659367, 0.650008, -0.645453, 0.987158, 0.396899, -1.34598, -0.556059]

larm020:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.272595, 0.0505544, 0.574014, 0.0351473, 0.043573, -1.12787, -0.17854]

larm021:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.251157, 0.815355, 0.928267, 0.563029, -1.11227, -1.43704, 0.125205]

larm022:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.652542, 1.39943, 0.429955, 0.859779, -1.75688, -1.43544, 0.148618]

larm023:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.617197, 0.856781, 0.324105, 1.11374, -1.14201, -1.53384, 0.229223]

larm024:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.516483, 0.806666, 0.76326, 0.52514, -1.4706, -1.26704, 0.58241]

larm025:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.564777, 0.805422, 0.640378, 0.36947, -1.77434, -1.40848, 0.952254]

larm026:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.663412, 0.902051, 0.248724, 1.27695, -0.777802, -1.33241, -0.23048]

larm027:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.263061, 0.463312, 1.13102, 0.0617498, -0.627178, -1.30563, -0.166853]

larm028:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.624361, 0.623906, 0.110439, 0.868135, -0.737918, -1.09055, 0.33421]

larm029:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.398505, 1.03909, 0.754746, 0.652635, -1.55713, -1.46873, 0.222336]

larm030:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.365515, 0.703761, 0.531208, 0.195885, -1.40399, -1.45378, 0.999925]

larm031:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.615347, 0.55389, -0.296335, 0.78449, -0.125713, -1.14982, -0.375077]

larm032:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.464532, 0.196572, 1.26251, 0.0598274, -1.00382, -1.04056, 0.702555]

larm033:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.517167, 0.745619, -0.637065, 0.478687, 0.440427, -1.45073, -0.266803]

larm034:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.644276, 0.949248, 0.587104, 1.12263, -0.902902, -1.50431, -0.472248]

larm035:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.516014, 1.05579, 0.807255, 0.860978, -1.80767, -1.52181, 0.762653]

larm036:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.479569, 0.769288, 0.501627, 0.347942, -1.67964, -1.3851, 1.00842]

larm037:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.370498, 0.0987268, 1.49065, -0.208981, -1.38044, -1.21715, 0.822437]

larm038:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.0212051, 0.178568, 0.586343, 0.341354, -0.288714, -0.994276, -0.0597929]

larm039:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.263669, 0.721511, 1.03625, 0.431397, -1.36003, -1.4155, 0.0870433]

larm040:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.128562, 0.265174, 1.16291, -0.0203923, -1.27067, -1.15699, 0.492187]

larm041:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.409524, 0.703398, 0.589505, 0.812896, -0.453702, -1.52145, -0.547269]

larm042:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.456781, 0.790791, 0.468199, 0.856467, -0.905, -1.13065, 0.172498]

larm043:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.361025, 0.87929, -0.324432, 0.957133, 0.242168, -1.52666, -0.290951]

larm044:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.0630398, 0.483893, 0.463985, 0.389951, -0.553961, -1.06579, 0.378266]

larm045:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.312749, 0.572314, 0.634352, 0.643524, -0.886381, -1.52463, -0.0775326]

larm046:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.585287, 1.03115, 0.519341, 0.908995, -1.35844, -1.48534, 0.516453]

larm047:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.174559, 0.410673, 0.952941, -0.226769, -1.42535, -1.42243, 1.16227]

larm048:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.468326, 0.521198, 0.376091, 0.0116548, -0.915856, -1.10046, 0.201231]

larm049:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [0.0842513, 0.603828, 1.27387, -0.285618, -1.51829, -1.43912, 0.840631]

larm050:
  joint_names: ["HeadPitch", "HeadYaw", "LShoulderPitch", "LShoulderRoll", "LElbowYaw", "LElbowRoll", "LWristYaw"]
  time_from_start: 1.0
  positions: [-0.152633, 0.312071, 0.762973, 0.268139, -0.759641, -1.18657, 0.200777]

